airflow:
  connections:
    - conn_id:
      conn_type:
      conn_host:
      conn_schema:
      conn_login:
      conn_password:
      conn_port:
      conn_extra:
  pools:
    - pool_name:
      pool_slot:
      pool_description:
  variables:
    - variable_name: gcp_project_id
      variable_value: YOUR_PROJECT_ID
    - variable_name: connector_id
      variable_value: YOUR_FIVETRAN_CONNECTOR
