airflow:
  connections:
    - conn_id: fivetran_default
      conn_type: Fivetran
    - conn_id: google_cloud_default
      conn_type: Google Cloud
  pools:
    - pool_name:
      pool_slot:
      pool_description:
  variables:
    - variable_name: gcp_project_id
      variable_value: 
    - variable_name: connector_id
      variable_value:
